"""Email delivery (Phase 9 sub-project A).

Renders the daily digest markdown as a multipart (plain-text + HTML) email and
sends it over SMTP. Built behind seams: a pure render core, a pure message
builder, one injectable network call, and a soft-failing orchestrator so a
delivery failure never breaks the run.

Transport is SMTP (Gmail locally); in the cloud the same code points at Amazon
SES's SMTP endpoint — only the config values change.
"""
from __future__ import annotations

import logging
import smtplib
from datetime import date
from email.message import EmailMessage

from markdown_it import MarkdownIt

from digest import config

log = logging.getLogger(__name__)

# html:False -> raw HTML in the markdown is escaped, not injected (XSS-safe, bug-070).
_MD = MarkdownIt("commonmark", {"html": False})

# Email clients ignore external stylesheets and are unreliable with <style> blocks,
# so EVERY style must be inline on the element. markdown-it emits predictable opening
# tags, so we post-process the rendered HTML and inject a style attr per tag. Light
# card + slate ink + amber accent (the app's "console" look, tuned for an inbox).
_TAG_STYLES = {
    "<h1>": '<h1 style="margin:0 0 6px;font-size:21px;font-weight:700;'
            'color:#16202c;letter-spacing:-.01em;line-height:1.3;">',
    "<h2>": '<h2 style="margin:28px 0 6px;font-size:16px;font-weight:600;'
            'color:#16202c;line-height:1.35;">',
    "<p>": '<p style="margin:0 0 10px;color:#3c4658;font-size:14.5px;line-height:1.55;">',
    "<a href=": '<a style="color:#b5641a;text-decoration:none;font-weight:600;" href=',
    "<hr />": '<hr style="border:none;border-top:1px solid #e4e8ee;margin:22px 0;" />',
    "<hr>": '<hr style="border:none;border-top:1px solid #e4e8ee;margin:22px 0;">',
    "<ul>": '<ul style="margin:6px 0 12px;padding-left:20px;color:#3c4658;font-size:14px;">',
    "<li>": '<li style="margin:3px 0;">',
    "<em>": '<em style="color:#5a657a;">',
    "<strong>": '<strong style="color:#16202c;font-weight:700;">',
}

# Outer page + centered white card with an amber top rule and a mono masthead eyebrow.
_HTML_SHELL = (
    '<div style="background:#f4f5f7;padding:24px 10px;margin:0;">'
    '<div style="max-width:640px;margin:0 auto;background:#ffffff;'
    'border-top:3px solid #d1791f;border-radius:6px;padding:26px 26px 22px;'
    "font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;"
    'color:#16202c;font-size:14.5px;line-height:1.55;">'
    '<div style="font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;'
    'font-size:11px;letter-spacing:.18em;text-transform:uppercase;color:#b5641a;'
    'font-weight:700;margin:0 0 12px;">Signal Digest</div>'
    "{body}"
    '<hr style="border:none;border-top:1px solid #e4e8ee;margin:24px 0 14px;" />'
    '<p style="margin:0;color:#8791a0;font-size:12px;line-height:1.5;">'
    "Generated by AI Trends Digest. Ranked and summarised by Claude.</p>"
    "</div></div>"
)


def _style_html(html: str) -> str:
    """Inject inline styles into markdown-it's opening tags (email-safe)."""
    for tag, styled in _TAG_STYLES.items():
        html = html.replace(tag, styled)
    return html


def render_email(markdown: str) -> tuple[str, str]:
    """(text, html) for a multipart email. PURE.

    text = the digest markdown unchanged (robust plain-text part).
    html = that markdown rendered to safe HTML, styled inline per element, inside a
    light card shell with the app's amber-accent masthead.
    """
    body = _style_html(_MD.render(markdown or ""))
    html = _HTML_SHELL.format(body=body)
    return markdown or "", html


def build_message(subject: str, from_addr: str, to_addr: str,
                  text: str, html: str) -> EmailMessage:
    """Assemble a multipart/alternative message. PURE (no I/O)."""
    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = from_addr
    msg["To"] = to_addr
    msg.set_content(text)                       # text/plain part
    msg.add_alternative(html, subtype="html")   # text/html part
    return msg


def _default_smtp() -> smtplib.SMTP_SSL:
    """Open an authenticated SMTP_SSL connection from config. The ONLY network I/O."""
    smtp = smtplib.SMTP_SSL(config.SMTP_HOST, config.SMTP_PORT)
    smtp.login(config.SMTP_USER, config.SMTP_PASSWORD)
    return smtp


def send_email(msg: EmailMessage, *, smtp_factory=_default_smtp) -> None:
    """Send one message. ``smtp_factory`` is injectable so tests pass a fake (no network)."""
    with smtp_factory() as smtp:
        smtp.send_message(msg)


def deliver_email(markdown: str, run_date: date, *, send_fn=send_email) -> bool:
    """Render + send the day's digest by email.

    Soft-fail: returns False (never raises) when unconfigured or on any send error
    — the digest file is already written, so delivery can't break the run.
    """
    if not config.EMAIL_ENABLED:
        log.info("email delivery not configured; skipping (digest saved to file).")
        return False
    subject = f"AI Trends Digest {run_date:%Y-%m-%d}"   # no em dash (user-facing)
    text, html = render_email(markdown)
    msg = build_message(subject, config.EMAIL_FROM, config.EMAIL_TO, text, html)
    try:
        send_fn(msg)
        log.info("emailed digest to %s", config.EMAIL_TO)
        return True
    except Exception as exc:  # noqa: BLE001 — one failed send must not break the run
        log.warning("email delivery failed (%s); digest still saved to file.", exc)
        return False
